
CREATE TABLE IF NOT EXISTS tbl_institute_form(
    form_id BIGINT NOT NULL AUTO_INCREMENT,
    form_unique_id BIGINT NOT NULL,
    institute_name VARCHAR(250) NOT NULL,
    inst_app_lic_no VARCHAR(250),
    license_type SMALLINT  NULL DEFAULT NULL,
    approval_doc_path TEXT,
    issue_date DOUBLE PRECISION,
    exp_date DOUBLE PRECISION,
    is_bqa_reviewed SMALLINT,
    review_issue_date DOUBLE PRECISION,
    review_jud_result TEXT,
    is_offering_nan_loc_course_qa SMALLINT,
    offering_description TEXT,
    planned_sub_date DOUBLE PRECISION,
    poc_name VARCHAR(250),
    poc_email VARCHAR(50),
    poc_cn_number TEXT,
    poc_title TEXT,
    status SMALLINT,
    resubmit_status SMALLINT,
    resubmit_count BIGINT,
    last_resubmit_date DOUBLE PRECISION,
    current_submit_date DOUBLE PRECISION,
    current_stage SMALLINT,
    date_ext_status SMALLINT,
    date_ext_reason TEXT,
    reqsted_ext_date DOUBLE PRECISION,
    is_extenstion_requested SMALLINT,
    form_flow_history TEXT,
    institution_id BIGINT,
    assigned_app_manager BIGINT,
    created_ip TEXT NOT NULL,
    updated_ip TEXT NOT NULL,
    created_app_id bigint NOT NULL,
    updated_app_id bigint NOT NULL,
    created_time DOUBLE PRECISION,
    last_updated_time DOUBLE PRECISION,
    PRIMARY KEY (form_id),
    UNIQUE KEY tbl_institute_form_unique_id (form_unique_id)
);



CREATE TABLE IF NOT EXISTS tbl_form_appln_manager(
    form_id BIGINT NOT NULL AUTO_INCREMENT,
    form_unique_id BIGINT NOT NULL,
    ip1 VARCHAR(250),
    ip1_status SMALLINT,
    ip1_status_comment TEXT,
    ip2 VARCHAR(250),
    ip2_status SMALLINT,
    ip2_status_comment TEXT,
    ip3 SMALLINT,
    ip3_status SMALLINT,
    ip3_status_comment TEXT,
    ip4 SMALLINT,
    ip4_status SMALLINT,
    ip4_status_comment TEXT,
    ip5_sub1 TEXT,
    ip5_sub2 DOUBLE PRECISION,
    ip5_sub3 DOUBLE PRECISION,
    ip5_status SMALLINT,
    ip5_status_comment TEXT,
    ip6 SMALLINT,
    ip6_status SMALLINT,
    ip6_status_comment TEXT,
    ip7 SMALLINT,
    ip7_status SMALLINT,
    ip7_status_comment TEXT,
    ip8_sub1 SMALLINT,
    ip8_sub2 TEXT,
    ip8_status SMALLINT,
    ip8_status_comment TEXT,
    ip9_sub_1 TEXT,
    ip9_sub_2 TEXT,
    ip9_sub_3 TEXT,
    ip9_status SMALLINT,
    ip9_status_comment TEXT,
    ip10_sub_1 TEXT,
    ip10_sub_2 TEXT,
    ip10_sub_3 TEXT,
    ip10_status SMALLINT,
    ip10_status_comment TEXT,
    ip11_sub_1 TEXT,
    ip11_sub_2 TEXT,
    ip11_sub_3 TEXT,
    ip11_sub_4 TEXT,
    ip11_status SMALLINT,
    ip11_status_comment TEXT,
    ip12_sub_1 TEXT,
    ip12_sub_2 TEXT,
    ip12_sub_3 TEXT,
    ip12_sub_4 TEXT,
    ip12_status SMALLINT,
    ip12_status_comment TEXT,
    qa_1 TEXT,
    qa_1_status SMALLINT,
    qa_1_status_comment TEXT,
    qa_2 TEXT,
    qa_2_status SMALLINT,
    qa_2_status_comment TEXT,
    qa_3 DOUBLE PRECISION,
    qa_3_status SMALLINT,
    qa_3_status_comment TEXT,
    qa_4 TEXT,
    qa_4_status SMALLINT,
    qa_4_status_comment TEXT,
    s1_atp_1_sub_1 TEXT,
    s1_atp_1_sub_2 TEXT,
    s1_atp_1_status SMALLINT,
    s1_atp_1_status_comment TEXT,
    s1_atp_2_sub_1 TEXT,
    s1_atp_2_sub_2 TEXT,
    s1_atp_2_status SMALLINT,
    s1_atp_2_status_comment TEXT,
    s1_atp_3_sub_1 TEXT,
    s1_atp_3_sub_2 TEXT,
    s1_atp_3_status SMALLINT,
    s1_atp_3_status_comment TEXT,
    s1_atp_4_sub_1 TEXT,
    s1_atp_4_sub_2 TEXT,
    s1_atp_4_status SMALLINT,
    s1_atp_4_status_comment TEXT,
    s1_atp_5_sub_1 TEXT,
    s1_atp_5_sub_2 TEXT,
    s1_atp_5_status SMALLINT,
    s1_atp_5_status_comment TEXT,
    s1_atp_6_sub_1 TEXT,
    s1_atp_6_sub_2 TEXT,
    s1_atp_6_status SMALLINT,
    s1_atp_6_status_comment TEXT,
    s2_qdar_1_sub_1 TEXT,
    s2_qdar_1_sub_2 TEXT,
    s2_qdar_1_status SMALLINT,
    s2_qdar_1_status_comment TEXT,
    s2_qdar_2_sub_1 TEXT,
    s2_qdar_2_sub_2 TEXT,
    s2_qdar_2_status SMALLINT,
    s2_qdar_2_status_comment TEXT,
    s2_qdar_3_sub_1 TEXT,
    s2_qdar_3_sub_2 TEXT,
    s2_qdar_3_status SMALLINT,
    s2_qdar_3_status_comment TEXT,
    s2_qdar_4_sub_1 TEXT,
    s2_qdar_4_sub_2 TEXT,
    s2_qdar_4_status SMALLINT,
    s2_qdar_4_status_comment TEXT,
    s2_qdar_5_sub_1 TEXT,
    s2_qdar_5_sub_2 TEXT,
    s2_qdar_5_status SMALLINT,
    s2_qdar_5_status_comment TEXT,
    s2_qdar_6_sub_1 TEXT,
    s2_qdar_6_sub_2 TEXT,
    s2_qdar_6_status SMALLINT,
    s2_qdar_6_status_comment TEXT,
    s3_adm_1_sub_1 TEXT,
    s3_adm_1_sub_2 TEXT,
    s3_adm_1_status SMALLINT,
    s3_adm_1_status_comment TEXT,
    s3_adm_2_sub_1 TEXT,
    s3_adm_2_sub_2 TEXT,
    s3_adm_2_status SMALLINT,
    s3_adm_2_status_comment TEXT,
    s3_adm_3_sub_1 TEXT,
    s3_adm_3_sub_2 TEXT,
    s3_adm_3_status SMALLINT,
    s3_adm_3_status_comment TEXT,
    s3_adm_4_sub_1 TEXT,
    s3_adm_4_sub_2 TEXT,
    s3_adm_4_status SMALLINT,
    s3_adm_4_status_comment TEXT,
    s3_adm_5_sub_1 TEXT,
    s3_adm_5_sub_2 TEXT,
    s3_adm_5_status SMALLINT,
    s3_adm_5_status_comment TEXT,
    s3_adm_6_sub_1 TEXT,
    s3_adm_6_sub_2 TEXT,
    s3_adm_6_status SMALLINT,
    s3_adm_6_status_comment TEXT,
    s3_adm_7_sub_1 TEXT,
    s3_adm_7_sub_2 TEXT,
    s3_adm_7_status SMALLINT,
    s3_adm_7_status_comment TEXT,
    s3_adm_8_sub_1 TEXT,
    s3_adm_8_sub_2 TEXT,
    s3_adm_8_status SMALLINT,
    s3_adm_8_status_comment TEXT,
    s3_adm_9_sub_1 TEXT,
    s3_adm_9_sub_2 TEXT,
    s3_adm_9_status SMALLINT,
    s3_adm_9_status_comment TEXT,
    s4_c_1_sub_1 TEXT,
    s4_c_1_sub_2 TEXT,
    s4_c_1_status SMALLINT,
    s4_c_1_status_comment TEXT,
    s4_c_2_sub_1 TEXT,
    s4_c_2_sub_2 TEXT,
    s4_c_2_status SMALLINT,
    s4_c_2_status_comment TEXT,
    s4_c_3_sub_1 TEXT,
    s4_c_3_sub_2 TEXT,
    s4_c_3_status SMALLINT,
    s4_c_3_status_comment TEXT,
    s5_scqi_1_sub_1 TEXT,
    s5_scqi_1_sub_2 TEXT,
    s5_scqi_1_status SMALLINT,
    s5_scqi_1_status_comment TEXT,
    s5_scqi_2_sub_1 TEXT,
    s5_scqi_2_sub_2 TEXT,
    s5_scqi_2_status SMALLINT,
    s5_scqi_2_status_comment TEXT,
    s5_scqi_3_sub_1 TEXT,
    s5_scqi_3_sub_2 TEXT,
    s5_scqi_3_status SMALLINT,
    s5_scqi_3_status_comment TEXT,
    ap_cont_1 TEXT,
    ap_cont_2 TEXT,
    ap_cont_3 TEXT,
    ap_cont_4 TEXT,
    overall_status SMALLINT,
    overall_status_comment TEXT,
    extra_evd_elabo_status SMALLINT,
    is_extenstion_requested SMALLINT,
    extension_requested_date DOUBLE PRECISION,
    extension_requested_status SMALLINT,
    reason_for_extension TEXT,
    created_by bigint,
    created_ip TEXT,
    updated_ip TEXT,
    created_app_id bigint,
    updated_app_id bigint,
    created_time DOUBLE PRECISION,
    last_updated_time DOUBLE PRECISION,
    PRIMARY KEY (form_id),
    UNIQUE KEY tbl_form_appln_manager_form_unique_id (form_unique_id)
);


CREATE TABLE IF NOT EXISTS tbl_app_mng_mapping(
    map_id BIGINT NOT NULL AUTO_INCREMENT,
    form_unique_id BIGINT NOT NULL,
    user_id BIGINT,
    user_type SMALLINT,
    created_by bigint,
    created_ip TEXT NOT NULL,
    updated_ip TEXT NOT NULL,
    created_app_id bigint NOT NULL,
    updated_app_id bigint NOT NULL,
    created_time DOUBLE PRECISION,
    last_updated_time DOUBLE PRECISION,
    PRIMARY KEY (map_id),
    UNIQUE KEY tbl_app_mng_mapping_unique_id (map_id)
);

